export const PROJECT_ACTIVITY_STATUS = Object.freeze({
  RUNNING: 1,
  TERMINATED: 2,
  OCCASIONALLY_ACTIVE: 3,
  SEASONAL: 4,
  UNDER_DEVELOPMENT: 5,
  HIATUS: 6,
})

export const MEMBER_ENGAGEMENT_TYPE = Object.freeze({
  MEMBER: 1,
  HIRED: 2,
  GUEST: 3,
})
