export const PROJECT_ACTIVITY_STATUS = Object.freeze({
  RUNNING: 1,
  TERMINATED: 2,
  OCCASIONALLY_ACTIVE: 3,
  SEASONAL: 4,
  UNDER_DEVELOPMENT: 5,
  HIATUS: 6,
})

export const PROJECT_MEMBER_STATUS = Object.freeze({
  PENDING: 1,
  ACCEPTED: 2,
  DECLINED: 3,
})
